export interface EmployeeRequest {
    id: number;
    first_name: string;
    last_name: string;
    full_name: string;
    chinese_name: string | null;
    email: string;
    phone: string | null;
    mobile: string | null;
    date_of_birth: string | null;
    gender: string | null;
    race: string | null;
    nric: string | null;
    nationality: string | null;
    nationality_id: number | null;
    nationality_name: string | null;
    residency_status: string | null;
    address_1: string | null;
    address_2: string | null;
    city: string | null;
    state: string | null;
    postal_code: string | null;
    country_id: number | null;
    country_name: string | null;
    emergency_name: string | null;
    emergency_relationship: string | null;
    emergency_contact: string | null;
    emergency_address_1: string | null;
    emergency_address_2: string | null;
    bank_name: string | null;
    bank_account_number: string | null;
    notes: string | null;
    profile_picture: string | null;
    status: 'pending' | 'approved' | 'rejected';
    status_label: string;
    status_severity: string;
    rejection_reason: string | null;
    approved_at: string | null;
    approved_by_name: string | null;
    rejected_at: string | null;
    rejected_by_name: string | null;
    created_at: string | null;
    updated_at: string | null;
}
