// Common nationalities (sorted alphabetically, with common ones at top)
export const nationalities = [
    'Singaporean',
    'Malaysian',
    'Chinese',
    'Indian',
    'Indonesian',
    'Filipino',
    'Vietnamese',
    'Thai',
    'Myanmar',
    'Bangladeshi',
    'Sri Lankan',
    'American',
    'Australian',
    'British',
    'Canadian',
    'French',
    'German',
    'Japanese',
    'Korean',
    'New Zealander',
    'Other',
] as const;

// Countries (ISO 3166-1, common ones first for Singapore context)
export const countries = [
    'Singapore',
    'Malaysia',
    'China',
    'India',
    'Indonesia',
    'Philippines',
    'Vietnam',
    'Thailand',
    'Myanmar',
    'Bangladesh',
    'Sri Lanka',
    'Australia',
    'Canada',
    'France',
    'Germany',
    'Hong Kong',
    'Japan',
    'New Zealand',
    'South Korea',
    'Taiwan',
    'United Kingdom',
    'United States',
    // Additional countries alphabetically
    'Afghanistan',
    'Albania',
    'Algeria',
    'Argentina',
    'Austria',
    'Belgium',
    'Brazil',
    'Brunei',
    'Cambodia',
    'Chile',
    'Colombia',
    'Czech Republic',
    'Denmark',
    'Egypt',
    'Finland',
    'Greece',
    'Hungary',
    'Ireland',
    'Israel',
    'Italy',
    'Kenya',
    'Laos',
    'Mexico',
    'Nepal',
    'Netherlands',
    'Nigeria',
    'Norway',
    'Pakistan',
    'Peru',
    'Poland',
    'Portugal',
    'Qatar',
    'Romania',
    'Russia',
    'Saudi Arabia',
    'South Africa',
    'Spain',
    'Sweden',
    'Switzerland',
    'Turkey',
    'Ukraine',
    'United Arab Emirates',
    'Other',
] as const;

// Emergency contact relationships
export const relationships = [
    'Spouse',
    'Parent',
    'Child',
    'Sibling',
    'Grandparent',
    'Grandchild',
    'Partner',
    'Friend',
    'Relative',
    'Guardian',
    'Other',
] as const;

// Helper to convert arrays to PrimeVue select options
export const nationalityOptions = nationalities.map((n) => ({ label: n, value: n }));
export const countryOptions = countries.map((c) => ({ label: c, value: c }));
export const relationshipOptions = relationships.map((r) => ({ label: r, value: r }));
